DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
    ID              VARCHAR2(50)
    , PWD           VARCHAR2(100)
    , NICK          VARCHAR2(50)
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , QUIT_YN       CHAR(1)         DEFAULT 'N'
);

INSERT INTO MEMBER (ID, PWD, NICK) VALUES ('user01','1234','包府磊');
commit;
--rollback;

DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD (
    TITLE             VARCHAR2(100)
    , CONTENT         VARCHAR2(4000)
    , ENROLL_DATE     TIMESTAMP      DEFAULT SYSDATE
    , DELETE_YN       CHAR(1)         DEFAULT 'N'
);

INSERT INTO BOARD (TITLE, CONTENT) VALUES ('力格1', '郴侩1');

SELECT ID, PWD, NICK, ENROLL_DATE, QUIT_YN FROM MEMBER WHERE ID = 'user09' AND PWD = 'aaa1234zzz' AND QUIT_YN = 'N'