ALTER USER C##KH DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--계정 생성
--CREATE USER ID IDENTIFIED BY PWD;
CREATE USER "C##KH" IDENTIFIED BY "KH";

--계정에 권한 부여
--GRANT 권한1,권한2 ... TO 계정명;
GRANT CONNECT,RESOURCE TO C##KH;

-- /**/ 주석
--SQL은 대문자로 작성

--테이블 생성 (CREATE)
CREATE TABLE MEMBER(
    ID VARCHAR2(30),
    PWD VARCHAR2(100)
);

--테이블 조회 (READ)
SELECT * FROM MEMBER;

--데이터 넣기 (INSERT)
INSERT INTO MEMBER(ID,PWD)VALUES('SWY','1234');

--데이터 수정 (UPDATE)
UPDATE MEMBER SET PWD = '4321';

--데이터 삭제 (DELETE)
DELETE MEMBER;

--테이블 삭제 (DROP)
DROP TABLE MEMBER;

