--------------------
--멤버
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
    NO          NUMBER          PRIMARY KEY
    , ID        VARCHAR2(50)    NOT NULL UNIQUE
    , PWD       VARCHAR2(100)   NOT NULL
    , NICK      VARCHAR2(50)    NOT NULL UNIQUE
    , GENDER    CHAR(1)         CHECK (GENDER IN ('M','F'))
    , MBTI      CHAR(4)
    , FILE_NAME VARCHAR2(100)   
    , STATUS    CHAR(1)         DEFAULT 'O' CHECK(STATUS IN ('O', 'X'))
    , ENROLL_DATE   TIMESTAMP   
    , MODIFY_DATE   TIMESTAMP   DEFAULT SYSDATE
);

DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;

--------------------
--보드
DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD(
    NO          NUMBER          PRIMARY KEY
    , TITLE     VARCHAR2(100)   NOT NULL
    , CONTENT   VARCHAR2(4000)  NOT NULL
    , WRITER    NUMBER          NOT NULL
    , HIT       NUMBER          DEFAULT 0
    , ENROLL_DATE   TIMESTAMP   DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP   DEFAULT SYSDATE
    , STATUS    CHAR(1)         DEFAULT 'O' CHECK(STATUS IN('O','X'))
    , CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER) REFERENCES MEMBER(NO)
);

DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;

--INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER) 
--VALUES (SEQ_BOARD_NO.NEXTVAL, '테스트', '테스트~', 1);

COMMIT;

--------------------
--댓글
DROP TABLE REPLY CASCADE CONSTRAINTS;
CREATE TABLE REPLY(
    NO          NUMBER          PRIMARY KEY
    , CONTENT   VARCHAR2(4000)  NOT NULL
    , BNO       NUMBER          NOT NULL
    , WRITER    NUMBER          NOT NULL
    , ENROLL_DATE   TIMESTAMP   DEFAULT SYSDATE
    , STATUS    CHAR(1)         DEFAULT 'O' CHECK(STATUS IN('O','X'))
    , CONSTRAINT FK_REPLY_BOARD FOREIGN KEY(BNO) REFERENCES BOARD(NO)
    , CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(WRITER) REFERENCES MEMBER(NO)
);

DROP SEQUENCE SEQ_REPLY_NO;
CREATE SEQUENCE SEQ_REPLY_NO NOCACHE NOCYCLE;
