--------------------
--¸â¹ö
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
    NO          NUMBER          PRIMARY KEY
    , ID        VARCHAR2(50)    NOT NULL UNIQUE
    , PWD       VARCHAR2(100)   NOT NULL
    , NICK      VARCHAR2(50)    NOT NULL UNIQUE
    , GENDER    CHAR(1)         CHECK (GENDER IN ('M','F'))
    , MBTI      CHAR(4)
    , FILE_NAME VARCHAR2(100)   
    , STATUS    CHAR(1)         DEFAULT 'O' CHECK(STATUS IN ('O', 'X'))
    , ENROLL_DATE   TIMESTAMP   
    , MODIFY_DATE   TIMESTAMP   DEFAULT SYSDATE
);

DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;

--------------------
--º¸µå
DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD(
    NO          NUMBER          PRIMARY KEY
    , TITLE     VARCHAR2(100)   NOT NULL
    , CONTENT   VARCHAR2(4000)  NOT NULL
    , WRITER    NUMBER          NOT NULL
    , HIT       NUMBER          DEFAULT 0
    , ENROLL_DATE   TIMESTAMP   DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP   DEFAULT SYSDATE
    , STATUS    CHAR(1)         DEFAULT 'O' CHECK(STATUS IN('O','X'))
    , CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER) REFERENCES MEMBER(NO)
);


DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;
