-- SEMI DDL

----------------------------
-- MEMBER
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(30)    NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NAME          VARCHAR2(15)    NOT NULL
    , PHONE         CHAR(13)        
    , EMAIL         VARCHAR2(100)   
    , ADDR          VARCHAR2(100)   
    , INTEREST      VARCHAR2(100)   
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP       DEFAULT SYSDATE
    , STATUS        CHAR(1)         DEFAULT 'N' CHECK(STATUS IN('Y','N'))
);

DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;

INSERT INTO MEMBER(NO, ID, PWD, NAME, PHONE, EMAIL, ADDR, INTEREST) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', '1234', '관리자', '01012341234', 'abc@yaho.com', '강남구 역삼동 테헤란로 1번길', NULL);

COMMIT;

---------------------------------
--NOTICE
DROP TABLE NOTICE CASCADE CONSTRAINTS;
CREATE TABLE NOTICE(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR(100)    NOT NULL
    , CONTENT       VARCHAR(4000)   NOT NULL
    , WRITER        NUMBER          NOT NULL
    , CNT           NUMBER          DEFAULT 0
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , STATUS        CHAR(1)         DEFAULT 'N' CHECK(STATUS IN('Y','N'))
);

ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_MEMBER FOREIGN KEY(WRITER) REFERENCES MEMBER(NO);

DROP SEQUENCE SEQ_NOTICE_NO;
CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE NOCYCLE;

INSERT INTO NOTICE(NO, TITLE, CONTENT, WRITER) VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항1', '내용1', 1);
INSERT INTO NOTICE(NO, TITLE, CONTENT, WRITER) VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항2', '내용2', 1);
INSERT INTO NOTICE(NO, TITLE, CONTENT, WRITER) VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항3', '내용3', 1);


COMMIT;

-----------------------------
--BOARD
DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD (
    NO              NUMBER          PRIMARY KEY
    , TYPE          NUMBER          --일반1/사진2
    , CATEGORY_NO   NUMBER          
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , WRITER        NUMBER          NOT NULL
    , CNT           NUMBER          DEFAULT 0
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , STATUS        CHAR(1)         DEFAULT 'N'
);

ALTER TABLE BOARD ADD CONSTRAINT BOARD_WRITER_MEMBER_NO FOREIGN KEY(WRITER) REFERENCES MEMBER(NO);

DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;

INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, 10, '제목', '내용', 1); 
COMMIT;

-----------------------------
--ATTACHMENT
DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE ATTACHMENT (
    NO              NUMBER          PRIMARY KEY
    , REF_BNO       NUMBER          NOT NULL
    , ORIGIN_NAME   VARCHAR2(255)   
    , CHANGE_NAME   VARCHAR2(255)   NOT NULL
    , FILE_PATH     VARCHAR2(1000)  NOT NULL
    , UPLOAD_DATE   TIMESTAMP       DEFAULT SYSDATE
    , FILE_LEVEL    NUMBER          
    , STATUS        CHAR(1)         DEFAULT 'N'
);

ALTER TABLE ATTACHMENT ADD CONSTRAINT ATT_BOARD_REF_BNO FOREIGN KEY(REF_BNO) REFERENCES BOARD;

DROP SEQUENCE SEQ_ATTACHMENT_NO;
CREATE SEQUENCE SEQ_ATTACHMENT_NO NOCACHE NOCYCLE;

-----------------------------
--CATEGORY

DROP TABLE CATEGORY CASCADE CONSTRAINTS;
CREATE TABLE CATEGORY (
    CATEGORY_NO     NUMBER          PRIMARY KEY
    , CATEGORY_NAME VARCHAR2(30)    NOT NULL
);

INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_NAME) VALUES(10, '공통');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_NAME) VALUES(20, '게임');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_NAME) VALUES(30, '운동');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_NAME) VALUES(40, '요리');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_NAME) VALUES(50, '음악');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_NAME) VALUES(60, '독서');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_NAME) VALUES(70, '그림');

COMMIT;

-----------------------------
--TEST

-- 특정 범위에 해당하는 게시글 ROW만 조회
SELECT * 
FROM (
    SELECT ROWNUM RNUM, T.*
    FROM
    (
        SELECT 
        B.NO
        , B.TITLE
        , B.CONTENT
        , B.CNT
        , B.ENROLL_DATE
        , M.ID AS WRITER
        , C.CATEGORY_NAME
        FROM BOARD B
        JOIN MEMBER M ON B.WRITER = M.NO
        JOIN CATEGORY C USING(CATEGORY_NO)
        WHERE B.TYPE = 1 AND B.STATUS = 'N'
        ORDER BY B.NO DESC
    ) T
)
WHERE RNUM BETWEEN ? AND ?
;

SELECT CATEGORY_NO, CATEGORY_NAME FROM CATEGORY;

INSERT INTO BOARD(NO, TYPE, CATEGORY_NO, TITLE, CONTENT, WRITER) VALUES(SEQ_BOARD_NO.NEXTVAL, 1, ?, ?, ?, ?);

INSERT INTO ATTACHMENT(NO, REF_BNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH) VALUES(SEQ_ATTACHMENT_NO, SEQ_BOARD_NO.CURRVAL, ?, ?, ?);
