-- UNION : 컬럼 타입, 갯수 일치해야
-- 결과집합을 연결해줌 (세로 형태로)
-- 실제 DB에는 없음

SELECT 10 첫번째칼럼, 20 두번째칼럼 FROM DUAL
UNION
SELECT 50 FIRSTCOL, 60 SECONDCOL FROM DUAL;

-- UNION
SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
UNION
SELECT 7777, 'SWY' FROM DUAL;

-- UNIONALL 중복표시
SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
UNION ALL
SELECT 7777, 'SWY' FROM DUAL;

-- INTERSECT 교집합
SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
INTERSECT
SELECT 7777, 'SWY' FROM DUAL;

-- MINUS 차집합
SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
MINUS
SELECT 7777, 'SWY' FROM DUAL;

