--webMiniPrj

-------------------
-- MEMBER
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
    NO      NUMBER          PRIMARY KEY
    ,ID     VARCHAR2(100)   NOT NULL UNIQUE
    ,PWD    VARCHAR2(100)   NOT NULL
    ,NAME   VARCHAR2(100)   NOT NULL
    ,NICK   VARCHAR2(100)   NOT NULL
    ,EMAIL  VARCHAR2(100)   NOT NULL
    ,PHONE  VARCHAR2(100)   NOT NULL
    ,ADDR   VARCHAR2(500)   NOT NULL
    ,E_DATE TIMESTAMP       DEFAULT SYSDATE
    ,STATUS CHAR(1)         DEFAULT 'Y'
    ,COMM VARCHAR2(500)  NULL
);

DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;

INSERT INTO MEMBER(NO, ID, PWD, NAME, NICK, EMAIL, PHONE, ADDR, COMM) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', '1234', '권효정', '관리자', 'admin@naver.com', '010-1234-1234', '경기도', '관리자입니다.');
COMMIT;

---------------------
--SELECT NO, ID, NAME, NICK, EMAIL, PHONE, ADDR, E_DATE FROM MEMBER WHERE ID = ? AND PWD = ? AND STATUS = 'Y';

---------------------
--BOARD
DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD (
    NO          NUMBER          PRIMARY KEY
    ,CATEGORY   VARCHAR2(50)    NOT NULL
    ,TITLE      VARCHAR2(100)   NOT NULL
    ,CONTENT    VARCHAR2(1000)  NOT NULL
    ,WRITER     VARCHAR2(100)   NOT NULL
    ,CNT        NUMBER          DEFAULT 0
    ,E_DATE     TIMESTAMP       DEFAULT SYSDATE
    ,STATUS     CHAR(1)         DEFAULT 'Y'
);

DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;

--INSERT INTO BOARD(NO, CATEGORY, TITLE, CONTENT, WRITER) VALUES(SEQ_BOARD_NO.NEXTVAL, '일반', '미니미홈 사용법', '게시글을 작성해 나를 알리고 다른 사람들의 관심사를 확인하세요', '관리자');
COMMIT;
---------------------
--SELECT NO, CATEGORY, TITLE, CONTENT, WRITER, CNT, E_DATE, STATUS FROM BOARD WHERE STATUS='Y';

--UPDATE MEMBER SET NICK = ?, EMAIL = ?, PHONE = ?, ADDR = ?, COMM = ? WHERE ID = ? AND NAME = ?;
