-- 그룹 나누기

SELECT AVG(SAL), DEPTNO --,ENAME불가 (GROUP 나누고 SELECT하기 때문에)
FROM EMP
WHERE COMM IS NOT NULL
GROUP BY DEPTNO
HAVING AVG(SAL) > 2000 --그룹핑 결과에 대한 조건 설정
ORDER BY DEPTNO DESC
;

--실행순서
--5. SELECT
--1. FROM
--2. WHERE
--3. GROUP BY
--4. HAVING
--6. ORDER BY