-- 집계
SELECT * FROM EMP;

-- GROUP BY
SELECT DEPTNO, JOB, SUM(SAL) 총급여
FROM EMP
GROUP BY DEPTNO, JOB
;

-- ROLLUP
SELECT DEPTNO, JOB, SUM(SAL) 총급여
FROM EMP
GROUP BY ROLLUP (DEPTNO, JOB)
;

-- CUBE
SELECT DEPTNO, JOB, SUM(SAL) 총급여
FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
;

--DELETE FROM EMP WHERE ENAME = 'SWY';
--COMMIT;

-- GROUPING SET
SELECT DEPTNO, JOB, SUM(SAL) 총급여
FROM EMP
GROUP BY GROUPING SETS(DEPTNO, JOB)
;

-- 소집계 보조 : ROLLUP, CUBE, GROUPING SET 3개 함수에 대해 보조
-- GROUPING

SELECT 
    DEPTNO --GROUPING(DEPTNO) 널값인지판단
    , CASE
        WHEN GROUPING(DEPTNO) = 1 THEN '부서번호제외통계'
        WHEN GROUPING(JOB) = 1 THEN 'JOB제외통계'
        ELSE '엘스'
    END "통계에서 제외한 컬럼"
    , JOB
    , SUM(SAL) 총급여
FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
;



SELECT * FROM MEMBER;

