DROP TABLE MEMBER CASCADE CONSTRAINTS;

CREATE TABLE MEMBER (
	M_NO	    NUMBER		                NOT NULL,
	M_CLASS	    NUMBER		                NOT NULL,
	M_REGNUM	NUMBER		                NOT NULL,
	M_NAME	    VARCHAR2(100)		        NOT NULL,
	M_ID	    VARCHAR2(100)		        NOT NULL,
	M_PWD	    VARCHAR2(100)		        NOT NULL,
	M_NICK  	VARCHAR2(100)		        NOT NULL,
	M_EMAIL 	VARCHAR2(100)		        NOT NULL,
	M_ADD	    VARCHAR2(100)		        NULL,
	M_PHONE 	VARCHAR2(100)		        NOT NULL,
	M_DATE  	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	M_DEL    	CHAR(1)	    DEFAULT 'N'	    NOT NULL,
	M_BAN	    CHAR(1)  	DEFAULT 'N'	    NOT NULL,
	M_MOD	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN MEMBER.M_CLASS IS '사용자/기업';

COMMENT ON COLUMN MEMBER.M_DEL IS 'Y/N';

COMMENT ON COLUMN MEMBER.M_BAN IS 'Y/N';

DROP TABLE Notice CASCADE CONSTRAINTS;

CREATE TABLE Notice (
	N_NO	    NUMBER		                NOT NULL,
	N_CATE	    VARCHAR2(100)		        NOT NULL,
	N_TITLE	    VARCHAR2(100)		        NOT NULL,
	N_CONTENT	VARCHAR2(1000)		        NOT NULL,
	N_CNT	    NUMBER	    DEFAULT 0	    NOT NULL,
	N_DATE	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	N_MOD	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN Notice.N_CATE IS '공지사항/FAQ';

DROP TABLE Donation CASCADE CONSTRAINTS;

CREATE TABLE Donation (
	D_NO	    NUMBER		            NOT NULL,
	REG_NO	    NUMBER		            NOT NULL,
	D_CLASS	    VARCHAR2(100)	    	NOT NULL,
	D_GMONEY	NUMBER		            NOT NULL,
	D_PMONEY	NUMBER	    DEFAULT 0	NOT NULL,
	D_SDATE	    TIMESTAMP		        NOT NULL,
	D_EDATE	    TIMESTAMP		        NOT NULL,
	D_PERSON	VARCHAR2(50)		    NOT NULL,
    D_PPEOPLE	NUMBER	    DEFAULT 0	NOT NULL
);

DROP TABLE Funding CASCADE CONSTRAINTS;

CREATE TABLE Funding (
	F_NO	    NUMBER		            NOT NULL,
	REG_NO	    NUMBER		            NOT NULL,
	F_CLASS	    VARCHAR2(100)		    NOT NULL,
	F_GMONEY	NUMBER		            NOT NULL,
	F_PMONEY	NUMBER      DEFAULT 0   NOT NULL,
    F_PPEOPLE	NUMBER	    DEFAULT 0	NOT NULL
);

DROP TABLE Campaign CASCADE CONSTRAINTS;

CREATE TABLE Campaign (
	CAM_NO	NUMBER		NOT NULL,
	REG_NO	NUMBER		NOT NULL,
	CAM_GPEOPLE	NUMBER		NOT NULL,
	CAM_PPEOPLE	NUMBER	DEFAULT 0	NOT NULL
);

DROP TABLE QA CASCADE CONSTRAINTS;

CREATE TABLE QA (
	QA_NO	    NUMBER		                NOT NULL,
	QA_NAME	    VARCHAR2(100)		        NOT NULL,
	QA_CONTENT	VARCHAR2(1000)		        NOT NULL,
	QA_DATE	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	QA_CATE	    VARCHAR2(100)		        NOT NULL,
	QA_ANSWER	VARCHAR2(1000)		        NOT NULL,
	QA_ADATE	TIMESTAMP		            NOT NULL,
	QA_DEL	    CHAR(1)	    DEFAULT 'N'	    NOT NULL,
	QA_SCORE	NUMBER		                NOT NULL
);

COMMENT ON COLUMN QA.QA_DEL IS 'Y/N';

COMMENT ON COLUMN QA.QA_SCORE IS '평점 매기기';

DROP TABLE Review CASCADE CONSTRAINTS;

CREATE TABLE Review (
	REV_NO	    NUMBER		                NOT NULL,
	M_NO	    NUMBER		                NOT NULL,
	REV_NAME	VARCHAR2(100)		        NOT NULL,
	REV_CONTENT	VARCHAR2(1000)		        NOT NULL,
	REV_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	REV_CLASS	VARCHAR2(100)		        NOT NULL,
	REV_MOD	    TIMESTAMP	DEFAULT SYSDATE	    NULL,
	REV_CNT	    NUMBER	    DEFAULT 0	    NOT NULL
);

COMMENT ON COLUMN Review.REV_CLASS IS '명세서 일반후기등';

DROP TABLE REPLY CASCADE CONSTRAINTS;

CREATE TABLE REPLY (
	REP_NO	    NUMBER		                NOT NULL,
	M_NO	    NUMBER		                NOT NULL,
	REG_NO	    NUMBER		                NOT NULL,
	REP_CONTENT	VARCHAR2(1000)		        NOT NULL,
	REP_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	REP_DEL	    CHAR(1)	    DEFAULT 'N'	    NOT NULL,
	REP_BAN	    CHAR(1)	    DEFAULT 'N'	    NOT NULL,
	REP_MOD	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN REPLY.REP_DEL IS 'Y/N';

COMMENT ON COLUMN REPLY.REP_BAN IS 'Y/N';

DROP TABLE Regist CASCADE CONSTRAINTS;

CREATE TABLE Regist (
	REG_NO	    NUMBER		                NOT NULL,
	M_NO	    NUMBER		                NOT NULL,
	REG_CLASS	VARCHAR2(100)		        NOT NULL,
	REG_NAME	VARCHAR2(100)		        NOT NULL,
	REG_CONTENT	VARCHAR2(4000)		        NOT NULL,
	REG_SDATE	TIMESTAMP		            NULL,
	REG_FDATE	TIMESTAMP		            NOT NULL,
	REG_PASS	CHAR(1)	    DEFAULT 'N' 	NOT NULL,
	REG_FIN	    CHAR(1)	    DEFAULT 'N'	    NOT NULL,
	REG_DEL	    CHAR(1) 	DEFAULT 'N'	    NOT NULL,
	REG_MOD	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	REG_CNT	    NUMBER	    DEFAULT 0	    NOT NULL,
    REG_DENY	VARCHAR2(100)		        NULL
);

COMMENT ON COLUMN Regist.REG_CLASS IS '기부/펀딩/캠페인';

COMMENT ON COLUMN Regist.REG_PASS IS 'Y/N';

COMMENT ON COLUMN Regist.REG_FIN IS 'Y/N';

COMMENT ON COLUMN Regist.REG_DEL IS 'Y/N';

DROP TABLE Reward CASCADE CONSTRAINTS;

CREATE TABLE Reward (
	REW_NO	    NUMBER		        NOT NULL,
	F_NO	    NUMBER		        NOT NULL,
	REW_NAME	VARCHAR2(100)		NOT NULL,
	REW_MONEY	NUMBER	        	NOT NULL,
	REW_COUNT	NUMBER	        	NOT NULL
);

DROP TABLE CampaignProof CASCADE CONSTRAINTS;

CREATE TABLE CampaignProof (
	CP_NO	    NUMBER		                NOT NULL,
	M_NO	    NUMBER		                NOT NULL,
	CAM_NO	    NUMBER		                NOT NULL,
	CP_CONTENT	VARCHAR2(1000)		        NOT NULL,
	CP_DATE	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	CP_DEL	    CHAR(1)	    DEFAULT 'N'	    NOT NULL,
	CP_BAN	    CHAR(1)	    DEFAULT 'N'	    NOT NULL,
	CP_MOD	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN CampaignProof.CP_DEL IS 'Y/N';

COMMENT ON COLUMN CampaignProof.CP_BAN IS 'Y/N';

DROP TABLE Pay CASCADE CONSTRAINTS;

CREATE TABLE Pay (
	P_NO	    NUMBER		        NOT NULL,
	M_NO	    NUMBER		        NOT NULL,
	P_NAME	    VARCHAR2(100)		NOT NULL,
	P_NUMBER	VARCHAR2(100)		NOT NULL
);

DROP TABLE PayList CASCADE CONSTRAINTS;

CREATE TABLE PayList (
	PL_NO	    NUMBER		                NOT NULL,
	REG_NO	    NUMBER		                NOT NULL,
	P_NO	    NUMBER		                NOT NULL,
	PL_DATE	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	PL_MONEY	NUMBER		                NOT NULL
);

DROP TABLE Corporation CASCADE CONSTRAINTS;

CREATE TABLE Corporation (
	CORP_NO 	    NUMBER		        NOT NULL,
	M_NO	        NUMBER		        NOT NULL,
	CORP_CONTENT	VARCHAR2(1000)		    NULL,
	CORP_CLASS	    VARCHAR2(100)		NOT NULL
);

DROP TABLE ReviewRegist CASCADE CONSTRAINTS;

CREATE TABLE ReviewRegist (
	RR_NO	NUMBER		NOT NULL,
	REV_NO	NUMBER		NOT NULL,
	REG_NO	NUMBER		NOT NULL,
	RR_CLASS	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN ReviewRegist.RR_CLASS IS '캠페인/기부/펀딩';

DROP TABLE RegImg CASCADE CONSTRAINTS;

CREATE TABLE RegImg (
	RI_NO	NUMBER		NOT NULL,
	REG_NO	NUMBER		NOT NULL,
	URL	VARCHAR2(100)		NOT NULL
);

DROP TABLE Manager CASCADE CONSTRAINTS;

CREATE TABLE Manager (
	MN_NO	NUMBER		NOT NULL,
	MN_ID	VARCHAR2(50)		NOT NULL,
	MN_PWD	VARCHAR2(50)		NOT NULL,
	MN_NICK	VARCHAR2(100)		NOT NULL
);

DROP TABLE RevImg CASCADE CONSTRAINTS;

CREATE TABLE RevImg (
	RVI_NO	NUMBER		NOT NULL,
	REV_NO	NUMBER		NOT NULL,
	URL	VARCHAR2(100)		NOT NULL
);

DROP TABLE Execute CASCADE CONSTRAINTS;

CREATE TABLE Execute (
	E_NO	NUMBER		NOT NULL,
	D_NO	NUMBER		NOT NULL,
	E_CTG	VARCHAR2(50)		NULL,
	E_CONTENT	VARCHAR2(200)		NULL,
	E_MONEY	VARCHAR2(50)		NULL
);

DROP TABLE ProofImg CASCADE CONSTRAINTS;

CREATE TABLE ProofImg (
	PR_NO	NUMBER		NOT NULL,
	CP_NO	NUMBER		NOT NULL,
	URL	VARCHAR2(100)		NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	M_NO
);

ALTER TABLE Notice ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
	N_NO
);

ALTER TABLE Donation ADD CONSTRAINT PK_DONATION PRIMARY KEY (
	D_NO
);

ALTER TABLE Funding ADD CONSTRAINT PK_FUNDING PRIMARY KEY (
	F_NO
);

ALTER TABLE Campaign ADD CONSTRAINT PK_CAMPAIGN PRIMARY KEY (
	CAM_NO
);

ALTER TABLE QA ADD CONSTRAINT PK_QA PRIMARY KEY (
	QA_NO
);

ALTER TABLE Review ADD CONSTRAINT PK_REVIEW PRIMARY KEY (
	REV_NO
);

ALTER TABLE REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY (
	REP_NO
);

ALTER TABLE Regist ADD CONSTRAINT PK_REGIST PRIMARY KEY (
	REG_NO
);

ALTER TABLE Reward ADD CONSTRAINT PK_REWARD PRIMARY KEY (
	REW_NO
);

ALTER TABLE CampaignProof ADD CONSTRAINT PK_CAMPAIGNPROOF PRIMARY KEY (
	CP_NO
);

ALTER TABLE Pay ADD CONSTRAINT PK_PAY PRIMARY KEY (
	P_NO
);

ALTER TABLE PayList ADD CONSTRAINT PK_PAYLIST PRIMARY KEY (
	PL_NO
);

ALTER TABLE Corporation ADD CONSTRAINT PK_CORPORATION PRIMARY KEY (
	CORP_NO
);

ALTER TABLE ReviewRegist ADD CONSTRAINT PK_REVIEWREGIST PRIMARY KEY (
	RR_NO
);

ALTER TABLE RegImg ADD CONSTRAINT PK_REGIMG PRIMARY KEY (
	RI_NO
);

ALTER TABLE Manager ADD CONSTRAINT PK_MANAGER PRIMARY KEY (
	MN_NO
);

ALTER TABLE RevImg ADD CONSTRAINT PK_REVIMG PRIMARY KEY (
	RVI_NO
);

ALTER TABLE Execute ADD CONSTRAINT PK_EXECUTE PRIMARY KEY (
	E_NO
);

ALTER TABLE ProofImg ADD CONSTRAINT PK_PROOFIMG PRIMARY KEY (
	PR_NO
);

ALTER TABLE Donation ADD CONSTRAINT FK_Regist_TO_Donation_1 FOREIGN KEY (
	REG_NO
)
REFERENCES Regist (
	REG_NO
);

ALTER TABLE Funding ADD CONSTRAINT FK_Regist_TO_Funding_1 FOREIGN KEY (
	REG_NO
)
REFERENCES Regist (
	REG_NO
);

ALTER TABLE Campaign ADD CONSTRAINT FK_Regist_TO_Campaign_1 FOREIGN KEY (
	REG_NO
)
REFERENCES Regist (
	REG_NO
);

ALTER TABLE Review ADD CONSTRAINT FK_MEMBER_TO_Review_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE REPLY ADD CONSTRAINT FK_MEMBER_TO_REPLY_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE REPLY ADD CONSTRAINT FK_Regist_TO_REPLY_1 FOREIGN KEY (
	REG_NO
)
REFERENCES Regist (
	REG_NO
);

ALTER TABLE Regist ADD CONSTRAINT FK_MEMBER_TO_Regist_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE Reward ADD CONSTRAINT FK_Funding_TO_Reward_1 FOREIGN KEY (
	F_NO
)
REFERENCES Funding (
	F_NO
);

ALTER TABLE CampaignProof ADD CONSTRAINT FK_MEMBER_TO_CampaignProof_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE CampaignProof ADD CONSTRAINT FK_Campaign_TO_CampaignProof_1 FOREIGN KEY (
	CAM_NO
)
REFERENCES Campaign (
	CAM_NO
);

ALTER TABLE Pay ADD CONSTRAINT FK_MEMBER_TO_Pay_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE PayList ADD CONSTRAINT FK_Regist_TO_PayList_1 FOREIGN KEY (
	REG_NO
)
REFERENCES Regist (
	REG_NO
);

ALTER TABLE PayList ADD CONSTRAINT FK_Pay_TO_PayList_1 FOREIGN KEY (
	P_NO
)
REFERENCES Pay (
	P_NO
);

ALTER TABLE Corporation ADD CONSTRAINT FK_MEMBER_TO_Corporation_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE ReviewRegist ADD CONSTRAINT FK_Review_TO_ReviewRegist_1 FOREIGN KEY (
	REV_NO
)
REFERENCES Review (
	REV_NO
);

ALTER TABLE ReviewRegist ADD CONSTRAINT FK_Regist_TO_ReviewRegist_1 FOREIGN KEY (
	REG_NO
)
REFERENCES Regist (
	REG_NO
);

ALTER TABLE RegImg ADD CONSTRAINT FK_Regist_TO_RegImg_1 FOREIGN KEY (
	REG_NO
)
REFERENCES Regist (
	REG_NO
);

ALTER TABLE RevImg ADD CONSTRAINT FK_Review_TO_RevImg_1 FOREIGN KEY (
	REV_NO
)
REFERENCES Review (
	REV_NO
);

ALTER TABLE Execute ADD CONSTRAINT FK_Donation_TO_Execute_1 FOREIGN KEY (
	D_NO
)
REFERENCES Donation (
	D_NO
);

ALTER TABLE ProofImg ADD CONSTRAINT FK_CampaignProof_TO_ProofImg_1 FOREIGN KEY (
	CP_NO
)
REFERENCES CampaignProof (
	CP_NO
);

COMMIT;

DROP SEQUENCE SEQ_MEMBER_M_NO;
CREATE SEQUENCE SEQ_MEMBER_M_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_NOTICE_N_NO;
CREATE SEQUENCE SEQ_NOTICE_N_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_DONATION_D_NO;
CREATE SEQUENCE SEQ_DONATION_D_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_FUNDING_F_NO;
CREATE SEQUENCE SEQ_FUNDING_F_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_CAMPAIGN_CAM_NO;
CREATE SEQUENCE SEQ_CAMPAIGN_CAM_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_QA_QA_NO;
CREATE SEQUENCE SEQ_QA_QA_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_REVIEW_REV_NO;
CREATE SEQUENCE SEQ_REVIEW_REV_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_REPLY_REP_NO;
CREATE SEQUENCE SEQ_REPLY_REP_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_REGIST_REG_NO;
CREATE SEQUENCE SEQ_REGIST_REG_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_REWARD_REW_NO;
CREATE SEQUENCE SEQ_REWARD_REW_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_CAMPAIGNPROOF_CP_NO;
CREATE SEQUENCE SEQ_CAMPAIGNPROOF_CP_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_PAY_P_NO;
CREATE SEQUENCE SEQ_PAY_P_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_PAYLIST_PL_NO;
CREATE SEQUENCE SEQ_PAYLIST_PL_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_CORPORATION_CORP_NO;
CREATE SEQUENCE SEQ_CORPORATION_CORP_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_REVIEWREGIST_RR_NO;
CREATE SEQUENCE SEQ_REVIEWREGIST_RR_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_REGIMG_RI_NO;
CREATE SEQUENCE SEQ_REGIMG_RI_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_MANAGER_MN_NO;
CREATE SEQUENCE SEQ_MANAGER_MN_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_REVIMG_RVI_NO;
CREATE SEQUENCE SEQ_REVIMG_RVI_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_EXECUTE_E_NO;
CREATE SEQUENCE SEQ_EXECUTE_E_NO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_PROOFIMG_PR_NO;
CREATE SEQUENCE SEQ_PROOFIMG_PR_NO NOCACHE NOCYCLE;


COMMIT;

--기업 KH마음재단 -- 안넣어봐서 잘 들어가는지 잘 몰라요... 확인필요
INSERT INTO MEMBER( M_NO , M_CLASS , M_REGNUM , M_NAME , M_ID , M_PWD , M_NICK , M_EMAIL , M_ADD , M_PHONE ) VALUES ( SEQ_MEMBER_M_NO.NEXTVAL , 2 , 02208264444 , '김하트' , 'kheart' , '1234' , 'KH마음재단' , 'kheart0826@yaho.com' , '서울시 강남구 역삼동 하트빌딩 2층' , '010-0808-2626' );
INSERT INTO CORPORATION (CORP_NO , M_NO , CORP_CONTENT , CORP_CLASS ) VALUES (SEQ_CORPORATION_CORP_NO.NEXTVAL, SEQ_MEMBER_M_NO.CURRVAL, 'KH마음재단은 나눔과 섬김, 사랑의 실천을 목적으로 설립된 국내외구호개발 단체입니다. KH마음재단은 인종, 사상, 지역, 성, 학력과 사외적 지위를 초월하여 지구촌 어디든 소외되고 고통받는 사람들을 위한 교류와 협력, 봉사 및 구호활동을 펼쳐나가고, 소상공인들을 위한 대행 판매 서비스 지원, 캠페인 활동들을 전개하며 그들의 역량을 강화하고 더불어 함께하는 세상을 만들어갑니다.', '비영리법인');

--일반 사용자 준혁님꺼 (아이디 소문자로 수정)
INSERT INTO MEMBER( M_NO , M_CLASS , M_REGNUM , M_NAME , M_ID , M_PWD , M_NICK , M_EMAIL , M_ADD , M_PHONE ) VALUES ( SEQ_MEMBER_M_NO.NEXTVAL , 1 , 9800001000000 , '박준혁' , 'user01' , '1234' , '학생입니다' , 'ABC@DE.F' , '강남구' , '01000001111' );

COMMIT;

INSERT INTO PAY VALUES(SEQ_PAY_P_NO.NEXTVAL, 2, '카드', 1111-2222-3333-4444);
INSERT INTO PAY VALUES(SEQ_PAY_P_NO.NEXTVAL, 2, '통장', 1210-415124-1234122);
INSERT INTO PAY VALUES(SEQ_PAY_P_NO.NEXTVAL, 2, '카드', 1111-2222-3333-4444);
INSERT INTO PAY VALUES(SEQ_PAY_P_NO.NEXTVAL, 2, '통장', 123121-111-798512);
INSERT INTO PAY VALUES(SEQ_PAY_P_NO.NEXTVAL, 2, '카드', 1111-2222-3333-4444);
INSERT INTO PAY VALUES(SEQ_PAY_P_NO.NEXTVAL, 2, '통장', 121-111111-555555);
INSERT INTO PAY VALUES(SEQ_PAY_P_NO.NEXTVAL, 2, '카드', 1111-2222-3333-4444);
INSERT INTO PAY VALUES(SEQ_PAY_P_NO.NEXTVAL, 2, '통장', 121-111111-444444);
COMMIT;