SELECT * FROM EMP;

SELECT EMPNO, ENAME, SAL*1.1 AS 급여 FROM EMP;

SELECT EMPNO, ENAME, 
    CASE
        WHEN COMM IS NOT NULL THEN SAL*2
        WHEN COMM IS NULL THEN SAL
    END 커미션급여
FROM EMP;

--급여가 높은 상위 3명 조회
SELECT * FROM
(SELECT * FROM EMP ORDER BY SAL DESC) --인라인뷰
WHERE ROWNUM <= 3;

--서브쿼리 (다중 열)
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, SAL 
                        FROM EMP 
                        WHERE DEPTNO = 30);
                        
--서브쿼리 (단일 행)
SELECT ENAME, DEPTNO, SAL,
    (SELECT TRUNC(AVG(SAL))
    FROM EMP
    WHERE DEPTNO = E.DEPTNO) AS 부서평균급여
FROM EMP E;

--상관쿼리
SELECT ENAME, JOB,
    (SELECT DNAME FROM DEPT WHERE DEPTNO = E.DEPTNO) DNAME
FROM EMP E;

--FROM 절 서브쿼리 (인라인뷰)

--ORDER BY 절 서브쿼리
SELECT EMPNO, ENAME, DEPTNO, HIREDATE
FROM EMP E
ORDER BY
(SELECT DNAME FROM DEPT WHERE DEPTNO = E.DEPTNO)
DESC;

--TRUNCATE
SELECT * FROM EMP;
