-- 시퀀스

-- 생성
DROP SEQUENCE MEMBER_NO_SEQ; --삭제

CREATE SEQUENCE MEMBER_NO_SEQ
INCREMENT BY 1 -- 증감숫자
 START WITH 1 -- 시작값rnjsgywjd
MINVALUE 1 -- 최소값
MAXVALUE 999 -- 최대값
NOCYCLE --CYCLE --순환 여부
NOCACHE --CACHE 100-- 캐시 여부 (사이즈)
;

-- 사용
SELECT MEMBER_NO_SEQ.NEXTVAL
FROM DUAL;

SELECT MEMBER_NO_SEQ.currval
FROM DUAL;

-- 수정
ALTER SEQUENCE MEMBER_NO_SEQ
INCREMENT BY 2
MINVALUE -10
MAXVALUE 123
CYCLE
CACHE 100
;