-- 제약조건
--PRIMARY KEY : 기본키(식별자)
--FORIGEN KEY : 외래키
--NOT NULL : NULL값 허용하지 않음
--UNIQUE : 중복방지
--DEFAULT : 기본으로 들어갈 값
--CHECK : 체크 조건 검사를 통과해야만 데이터 저장 가능

DROP TABLE ZZZ;

-- NOT NULL
CREATE TABLE ZZZ(
    ID VARCHAR2(100) NOT NULL
);
-- 테이블 생성 이후에도 제약조건 수정 가능
ALTER TABLE ZZZ MODIFY ID VARCHAR2(100) NOT NULL;

-- DEFAULT
CREATE TABLE ZZZ(
    ID VARCHAR2(100) DEFAULT 'ADMIN'
);
ALTER TABLE ZZZ MODIFY ID VARCHAR2(100) DEFAULT 'HONGGILDONG';

-- CHECK
CREATE TABLE ZZZ(
    ID VARCHAR2(100) CHECK(ID.LENGTH < 10)
);
ALTER TABLE ZZZ ADD CONSTRAINT ZZZIDCHECK 
CHECK(REGEXP_LIKE(PHONEm,'^010-\d{3,4}-\d{4}$'));

-- PRIMARY KEY
CREATE TABLE ZZZ(
    ID VARCHAR2(100) PRIMARY KEY
);

CREATE TABLE ZZZ(
    ID VARCHAR2(100),
    CONSTRAINT ZZZTBPK PRIMARY KEY(ID)
);

ALTER TABLE ZZZ
ADD CONSTRAINT ZZZTBPK PRIMARY KEY(ID);

-- UNIQUE
CREATE TABLE ZZZ(
    ID VARCHAR2(100) UNIQUE
);

ALTER TABLE ZZZ
ADD CONSTRAINT ZZZTBIDUQ UNIQUE(ID);

-- FOREIGN KEY
DROP TABLE STUDENT;

CREATE TABLE STUDENT(
    NO NUMBER PRIMARY KEY
    , NAME VARCHAR2(100)
);
SELECT * FROM SCORE;

DROP TABLE SCORE;

CREATE TABLE SCORE(
    STD_NO NUMBER
    , GRADE CHAR(2),
    CONSTRAINT STDFK FOREIGN KEY(STD_NO) REFERENCES STUDENT(NO) ON DELETE SET NULL --ON DELETE CASCADE
);

INSERT INTO STUDENT(NO, NAME)
VALUES(1, 'JAVA');
--COMMIT;

INSERT INTO SCORE(STD_NO, GRADE)
VALUES(5, 'A');
--COMMIT;



SELECT * FROM MEMBER;

INSERT INTO MEMBER(NO, PWD) VALUES(1, '1234');

INSERT INTO MEMBER(NO, ID, PWD) VALUES(1, 'SWY', '1234');

INSERT INTO MEMBER(NO, ID, PWD, QUIT_YN) VALUES(1, 'SWY', '1234','X');