-- 제약조건
--PRIMARY KEY
--FORIGEN KEY
--NOT NULL
--UNIQUE
--DEFAULT
--CHECK

DROP TABLE MEMBER;

CREATE TABLE MEMBER(
      NO NUMBER PRIMARY KEY
    , ID VARCHAR2(100) UNIQUE
    , PWD VARCHAR2(100)
    , QUIT_YN CHAR(1) DEFAULT 'N' 
    CHECK (QUIT_YN IN ('N','Y'))
);

SELECT * FROM MEMBER;

INSERT INTO MEMBER(NO, PWD) VALUES(1, '1234');

INSERT INTO MEMBER(NO, ID, PWD) VALUES(1, 'SWY', '1234');

INSERT INTO MEMBER(NO, ID, PWD, QUIT_YN) VALUES(1, 'SWY', '1234','X');