--트리거

--DML 테스트
INSERT INTO BOARD VALUES('제목01','안녕하세요');
UPDATE BOARD SET CONTENT = '변경된내용' WHERE TITLE = '제목01';
UPDATE BOARD SET CONTENT = '한번더변경된내용' WHERE TITLE = '제목01';
DELETE BOARD WHERE TITLE = '제목01';

--조회
SELECT '===원본===' AS 제목 ,'===원본===' AS 내용 FROM DUAL
UNION ALL
SELECT * FROM BOARD
UNION ALL
SELECT '===사본===' AS 제목 ,'===사본===' FROM DUAL
UNION ALL
SELECT * FROM BOARD_COPY
UNION ALL
SELECT '===기록===' AS 제목 ,'===기록===' FROM DUAL
UNION ALL
SELECT * FROM BOARD_LOG
UNION ALL
SELECT '===삭제===' AS 제목 ,'===삭제===' FROM DUAL
UNION ALL
SELECT * FROM BOARD_TRASH
UNION ALL
SELECT '========' AS 제목 ,'========' FROM DUAL
UNION ALL
SELECT 'DML횟수' , TO_CHAR(CNT) FROM BOARD_DML_CNT
;