--트리거

--원본 테이블
DROP TABLE BOARD;
CREATE TABLE BOARD(
    TITLE VARCHAR2(100)
    , CONTENT VARCHAR2(100)
);

--카피 테이블 (INSERT 발생시 복사)
DROP TABLE BOARD_COPY;
CREATE TABLE BOARD_COPY(
    TITLE VARCHAR2(100)
    , CONTENT VARCHAR2(100)
);

-- 행 삭제시, 저장할 테이블
DROP TABLE BORAD_TRASH;
CREATE TABLE BOARD_TRASH(
    TITLE VARCHAR2(100)
    , CONTENT VARCHAR2(100)
);

-- 행 수정시, 기록 남길 테이블
DROP TABLE BORAD_LOG;
CREATE TABLE BOARD_LOG(
    TITLE VARCHAR2(100)
    , CONTENT VARCHAR2(100)
);

-- DML 수행 횟수 기록
DROP TABLE BOARD_DML_CNT;
CREATE TABLE BOARD_DML_CNT(
    CNT NUMBER
);
