-- Æ®¸®°Å

CREATE OR REPLACE TRIGGER TRG_BOARD
AFTER INSERT OR DELETE OR UPDATE ON BOARD
FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO BOARD_COPY(TITLE, CONTENT) VALUES(:NEW.TITLE, :NEW.CONTENT);
        END IF;
        IF DELETING THEN
            INSERT INTO BOARD_TRASH(TITLE, CONTENT) VALUES(:OLD.TITLE, :OLD.CONTENT);
        END IF;
        IF UPDATING THEN
            INSERT INTO BOARD_LOG(TITLE, CONTENT) VALUES(:OLD.TITLE, :OLD.CONTENT || '=>' || :NEW.CONTENT);
        END IF;
    END TRG_BOARD;
