-- 함수 (날짜)

/*
    SYSDATE
    SYSTIMESTAMP **
    CURRENT_TIMESTAMP
    CURRENT_DATE
*/

SELECT SYSDATE FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
SELECT CURRENT_TIMESTAMP FROM DUAL;
SELECT CURRENT_DATE FROM DUAL;

--EXTRACT : 추출
--YEARM MONTH DAY HOUR MINUTE SECOND
SELECT 
    EXTRACT(YEAR FROM SYSTIMESTAMP) 년도
  , EXTRACT(MONTH FROM SYSTIMESTAMP) 월
FROM DUAL;

--NEXT_DAY : 가장 가까운 다음 날짜 (요일 지정)
SELECT NEXT_DAY(SYSDATE, '금')
FROM DUAL;

--TO_DATE : 날짜타입으로 변환
SELECT TO_DATE('2022/5/19')
FROM DUAL;

--BETWEEN
SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2021/05/19'))
FROM DUAL;

--LAST_DAY : 이달의 마지막 날짜
SELECT LAST_DAY(SYSDATE)
FROM DUAL;

--ROUND
SELECT ROUND(SYSDATE, 'MONTH')
FROM DUAL;

--TRUNC
SELECT TRUNC(TO_DATE('22/12/20'), 'MONTH')
FROM DUAL;

