-- 순위

SELECT ROW_NUMBER() OVER(ORDER BY HIREDATE) AS RN, E.*
FROM EMP E
;

SELECT RANK() OVER(ORDER BY HIREDATE) AS RN, E.*
FROM EMP E
;

SELECT DENSE_RANK() OVER(ORDER BY HIREDATE) AS RN, E.*
FROM EMP E
;

-- 그룹 나눠서 랭킹
SELECT RANK() OVER(PARTITION BY DEPTNO ORDER BY HIREDATE) AS RN, E.*
FROM EMP E
;

SELECT ROWNUM, E.* --순서이상하게 나옴
FROM EMP E
ORDER BY HIREDATE
;

